### ISSUE TITLE
v0.3 roadmap

### ISSUE THREAD

**Issue by aaronchenwei** [aaronchenwei/tslint-config#6]
- [ ] To remove dependency to `tslint-config-airbnb`
- [ ] To remove dependency to `tslint-config-prettier`
- [ ] others to be decided...

**Comment by aaronchenwei** [comment]
close with PR #15
